language: node_js
node_js:
  - "6.11.3"
cache:
  directories:
    - "node_modules"
install:
  - "npm install"
script:
  - "wget -O src/config.json $CONFIG_HREF"
  - "npm run test"
  - "npm run build"
